name: howmany
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
    - snakemake-minimal=5.3.0
    - pyyaml=5.1
    - fastp=0.19.7
    - r-tidyverse=1.2.1
    - r-optparse=1.6.1
    - seqtk = 1.2
    - pandas = 0.25.0
    - tar = 1.29
    - hisat2 = 2.1.0 
    - subread = 1.6.4 
