---
# sample information
samples : samples.tsv

# working directories
workdir: scratch/
resultdir: results/

# trimming parameters
fastp:
  qualified_quality_phred: 15 # the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified. (int [=15])

# kallisto fasta file that will be indexed by Kallisto
kallisto:
  fasta_ref: rules/refs/ITAG4.0_cDNA.fasta
  fragment-length: 90
  sd: 30
  bootstrap: 100
