---
# sample information
samples : samples.tsv

# working directories
workdir: scratch/
resultdir: results/

# trimming parameters
fastp:
  qualified_quality_phred: 15 # the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified. (int [=15])

# kallisto fasta file that will be indexed by Kallisto
refs:
  genome: rules/refs/S_lycopersicum_chromosomes.4.00.fa
  gff: rules/refs/ITAG4.0_gene_models.gff 

# parameters for subsetting reads (rarefaction curve)
# note: it always ends at 100% (= original sample)
subset:
  start: 10  # initial subsetted sample at 10%
  step: 10  # step of 10% (e.g. will make 10 samples using 10%, 20%, 30%, ..., 100% of the initial reads)